import "@/styles/index.css";
import { Providers } from "./providers";

export const metadata = {
  title: {
    default: "Merax Next",
    template: "Merax Next | %s",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
  openGraph: {
    title: "Merax Next (opengraph)",
    description: "Generated by create next app (opengraph)",
  },
  twitter: {
    title: "Merax Next (twitter)",
    description: "Generated by create next app (twitter)",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
