import "@/styles/index.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Merax Next",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
